version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "cargo"
    directories:
      - "/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"
