[package]
name = "game-library-frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = { version = "^0.12", features = ["with-axum"] }
askama_axum = "^0.4"
axum = { version = "^0.7", features = ["http1", "http2", "macros", "query", "tokio"] }
tokio = { version = "^1", features = ["full"] }
tower = { version = "^0.4", features = ["buffer", "limit"] }
tower-http = { version = "^0.5", features = ["fs"] }
