[package]
name = "game-library-frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "^0.12"
axum = { version = "^0.7", features = ["http1", "http2", "macros", "query", "tokio"] }
axum-extra = { version = "^0.9", features = ["cookie"] }
base64 = "^0.21"
hex = "^0.4"
hmac = "^0.12"
mime = "^0.3"
rand = "^0.8"
reqwest = { version = "^0.11", features = ["cookies", "json"] }
serde = { version = "^1", features = ["derive"] }
sha2 = "^0.10"
tokio = { version = "^1", features = ["full"] }
tower = { version = "^0.4", features = ["buffer", "limit"] }
tower-http = { version = "^0.5", features = ["fs"] }
urlencoding = "^2"
